source 'https://rubygems.org'

gem 'fog',           github: 'fog/fog', ref: '91c3b6f'
gem 'fog-core',      github: 'fog/fog-core'
gem 'net-ssh-shell', github: 'joshk/net-ssh-shell'
gem 'faraday'
gem 'multi_json'
gem 'thor'
gem 'hashr'
gem 'activesupport'
gem 'travis-saucelabs-api', github: 'henrikhodne/travis-saucelabs-api'
