source 'https://rubygems.org'

gem 'fog'
gem 'net-ssh-shell'
gem 'faraday'
gem 'multi_json'
gem 'thor'
gem 'hashr'
gem 'activesupport'
gem 'travis-saucelabs-api', github: 'henrikhodne/travis-saucelabs-api'
